import type { Metadata } from "next";
//import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/NavBar";
import Footer from "@/components/Footer";
import { Lato } from 'next/font/google';
import MoldeDuvidas from "@/components/moldeDuvidas";

//const geistSans = localFont({
//  src: "./fonts/GeistVF.woff",
//  variable: "--font-geist-sans",
//  weight: "100 900",
//});
//const geistMono = localFont({
//  src: "./fonts/GeistMonoVF.woff",
//  variable: "--font-geist-mono",
//  weight: "100 900",
//});

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={lato.className}>
        <Navbar />
        {children}
        <MoldeDuvidas/>
        <Footer/>
      </body>
    </html>
  );
}
